/**
 * Single source of truth for "is this squabble over, and what do we call it?"
 *
 * Why this exists: the dashboard used to bucket cards with `status === "open"`
 * while `squabble-card.tsx` derived its badge from `isExpired(expires_at)`.
 * Those two predicates disagree for exactly one row shape — expired but still
 * marked `open` — and that shape is guaranteed to exist, because closing is
 * lazy (written on first read after expiry). The result was a card sitting
 * under "Live now" wearing a "Closed" badge.
 *
 * Both callers now derive from `resolveSquabbleStatus`, so the bucket and the
 * badge cannot drift apart again: `settled` and `label` come out of one branch.
 */

import { isExpired } from "@/lib/utils";

export type SquabbleStatusKey = "live" | "counting" | "decided" | "no-winner";

export type ResolvedSquabbleStatus = {
  key: SquabbleStatusKey;
  label: string;
  /** True once voting is over, whether or not the close has been written yet. */
  settled: boolean;
};

type SquabbleStatusInput = {
  status: string;
  winnerSide: "a" | "b" | null;
  expiresAt: string | Date;
};

export const resolveSquabbleStatus = ({
  status,
  winnerSide,
  expiresAt,
}: SquabbleStatusInput): ResolvedSquabbleStatus => {
  if (status === "open") {
    // Still open in the DB. The timer is the tiebreaker: an expired row is over
    // even though `closeSquabble` hasn't written the outcome yet. We know it's
    // finished; we don't yet know who won, so don't claim one.
    return isExpired(expiresAt)
      ? { key: "counting", label: "Counting votes", settled: true }
      : { key: "live", label: "Live", settled: false };
  }

  return winnerSide
    ? { key: "decided", label: "Decided", settled: true }
    : { key: "no-winner", label: "No winner", settled: true };
};

/**
 * Did this voter back the winning side?
 *
 * Null-safe on both sides: no vote, or no winner (a tie), means nobody won and
 * the celebration must not fire. Exported so the test asserts on the shipped
 * predicate rather than on `"a" === "a"`.
 */
/**
 * Badge classes per status.
 *
 * Passed as `className` rather than expressed as CSS overrides: the Badge
 * already ships a `bg-*` utility from its `variant`, and overriding that from a
 * stylesheet meant depending on cascade-layer ordering that did not hold in
 * practice. `cn()` runs twMerge, which drops the earlier conflicting `bg-*`, so
 * the status colour wins deterministically — no !important, no layer games.
 *
 * Fixed palette colours, deliberately, rather than `bg-primary` / `bg-foreground`
 * or `bg-[var(--status-live-bg,...)]`:
 *   - arbitrary values containing a nested `var()` with a comma were never
 *     generated by Tailwind, so those classes styled nothing at all;
 *   - the semantic tokens did not resolve to the active theme's values on this
 *     element, so `bg-foreground` rendered near-black on the near-black Molten
 *     and Impact backgrounds.
 * These four read correctly on every theme's background, light or dark.
 *
 * Colour is never the only signal — the label text differs for every status too,
 * which is what carries the meaning for anyone who can't separate these hues.
 */
export const STATUS_BADGE_CLASSES: Record<SquabbleStatusKey, string> = {
  live: "bg-emerald-600 text-white",
  counting: "bg-amber-500 text-black",
  decided: "bg-blue-600 text-white font-semibold",
  "no-winner": "bg-zinc-500 text-white",
};

export const didVoterWin = (
  userVote: "a" | "b" | null,
  winnerSide: "a" | "b" | null,
): boolean => userVote !== null && winnerSide !== null && userVote === winnerSide;
